// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: cluster.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterServiceClient interface {
	// 获取集群状态
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error)
	// 设置集群配置
	SetClusterConfig(ctx context.Context, in *SetClusterConfigRequest, opts ...grpc.CallOption) (*SetClusterConfigResponse, error)
	// 强制负载均衡
	ForceLoadBalancing(ctx context.Context, in *ForceLoadBalancingRequest, opts ...grpc.CallOption) (*ForceLoadBalancingResponse, error)
	// 迁移流
	MigrateStream(ctx context.Context, in *MigrateStreamRequest, opts ...grpc.CallOption) (*MigrateStreamResponse, error)
	// 优化资源分配
	OptimizeResources(ctx context.Context, in *OptimizeResourcesRequest, opts ...grpc.CallOption) (*OptimizeResourcesResponse, error)
	// 获取监控指标
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error) {
	out := new(GetClusterStatusResponse)
	err := c.cc.Invoke(ctx, "/pb.ClusterService/GetClusterStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) SetClusterConfig(ctx context.Context, in *SetClusterConfigRequest, opts ...grpc.CallOption) (*SetClusterConfigResponse, error) {
	out := new(SetClusterConfigResponse)
	err := c.cc.Invoke(ctx, "/pb.ClusterService/SetClusterConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ForceLoadBalancing(ctx context.Context, in *ForceLoadBalancingRequest, opts ...grpc.CallOption) (*ForceLoadBalancingResponse, error) {
	out := new(ForceLoadBalancingResponse)
	err := c.cc.Invoke(ctx, "/pb.ClusterService/ForceLoadBalancing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) MigrateStream(ctx context.Context, in *MigrateStreamRequest, opts ...grpc.CallOption) (*MigrateStreamResponse, error) {
	out := new(MigrateStreamResponse)
	err := c.cc.Invoke(ctx, "/pb.ClusterService/MigrateStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) OptimizeResources(ctx context.Context, in *OptimizeResourcesRequest, opts ...grpc.CallOption) (*OptimizeResourcesResponse, error) {
	out := new(OptimizeResourcesResponse)
	err := c.cc.Invoke(ctx, "/pb.ClusterService/OptimizeResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, "/pb.ClusterService/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/pb.ClusterService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility
type ClusterServiceServer interface {
	// 获取集群状态
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error)
	// 设置集群配置
	SetClusterConfig(context.Context, *SetClusterConfigRequest) (*SetClusterConfigResponse, error)
	// 强制负载均衡
	ForceLoadBalancing(context.Context, *ForceLoadBalancingRequest) (*ForceLoadBalancingResponse, error)
	// 迁移流
	MigrateStream(context.Context, *MigrateStreamRequest) (*MigrateStreamResponse, error)
	// 优化资源分配
	OptimizeResources(context.Context, *OptimizeResourcesRequest) (*OptimizeResourcesResponse, error)
	// 获取监控指标
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct {
}

func (UnimplementedClusterServiceServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedClusterServiceServer) SetClusterConfig(context.Context, *SetClusterConfigRequest) (*SetClusterConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetClusterConfig not implemented")
}
func (UnimplementedClusterServiceServer) ForceLoadBalancing(context.Context, *ForceLoadBalancingRequest) (*ForceLoadBalancingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceLoadBalancing not implemented")
}
func (UnimplementedClusterServiceServer) MigrateStream(context.Context, *MigrateStreamRequest) (*MigrateStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateStream not implemented")
}
func (UnimplementedClusterServiceServer) OptimizeResources(context.Context, *OptimizeResourcesRequest) (*OptimizeResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptimizeResources not implemented")
}
func (UnimplementedClusterServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedClusterServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClusterService/GetClusterStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_SetClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).SetClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClusterService/SetClusterConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).SetClusterConfig(ctx, req.(*SetClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ForceLoadBalancing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceLoadBalancingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ForceLoadBalancing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClusterService/ForceLoadBalancing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ForceLoadBalancing(ctx, req.(*ForceLoadBalancingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_MigrateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).MigrateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClusterService/MigrateStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).MigrateStream(ctx, req.(*MigrateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_OptimizeResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).OptimizeResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClusterService/OptimizeResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).OptimizeResources(ctx, req.(*OptimizeResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClusterService/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClusterService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterStatus",
			Handler:    _ClusterService_GetClusterStatus_Handler,
		},
		{
			MethodName: "SetClusterConfig",
			Handler:    _ClusterService_SetClusterConfig_Handler,
		},
		{
			MethodName: "ForceLoadBalancing",
			Handler:    _ClusterService_ForceLoadBalancing_Handler,
		},
		{
			MethodName: "MigrateStream",
			Handler:    _ClusterService_MigrateStream_Handler,
		},
		{
			MethodName: "OptimizeResources",
			Handler:    _ClusterService_OptimizeResources_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ClusterService_GetMetrics_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ClusterService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}
