// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: stream.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	// 注册流
	RegisterStream(ctx context.Context, in *RegisterStreamRequest, opts ...grpc.CallOption) (*RegisterStreamResponse, error)
	// 注销流
	UnregisterStream(ctx context.Context, in *UnregisterStreamRequest, opts ...grpc.CallOption) (*UnregisterStreamResponse, error)
	// 获取流信息
	GetStreamInfo(ctx context.Context, in *GetStreamInfoRequest, opts ...grpc.CallOption) (*GetStreamInfoResponse, error)
	// 获取集群流列表
	GetClusterStreams(ctx context.Context, in *GetClusterStreamsRequest, opts ...grpc.CallOption) (*GetClusterStreamsResponse, error)
	// 获取发布者最优节点
	GetOptimalNodeForPublisher(ctx context.Context, in *GetOptimalNodeForPublisherRequest, opts ...grpc.CallOption) (*GetOptimalNodeForPublisherResponse, error)
	// 获取订阅者最优节点
	GetOptimalNodeForSubscriber(ctx context.Context, in *GetOptimalNodeForSubscriberRequest, opts ...grpc.CallOption) (*GetOptimalNodeForSubscriberResponse, error)
	// 更新流状态
	UpdateStreamState(ctx context.Context, in *UpdateStreamStateRequest, opts ...grpc.CallOption) (*UpdateStreamStateResponse, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) RegisterStream(ctx context.Context, in *RegisterStreamRequest, opts ...grpc.CallOption) (*RegisterStreamResponse, error) {
	out := new(RegisterStreamResponse)
	err := c.cc.Invoke(ctx, "/pb.StreamService/RegisterStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) UnregisterStream(ctx context.Context, in *UnregisterStreamRequest, opts ...grpc.CallOption) (*UnregisterStreamResponse, error) {
	out := new(UnregisterStreamResponse)
	err := c.cc.Invoke(ctx, "/pb.StreamService/UnregisterStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetStreamInfo(ctx context.Context, in *GetStreamInfoRequest, opts ...grpc.CallOption) (*GetStreamInfoResponse, error) {
	out := new(GetStreamInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.StreamService/GetStreamInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetClusterStreams(ctx context.Context, in *GetClusterStreamsRequest, opts ...grpc.CallOption) (*GetClusterStreamsResponse, error) {
	out := new(GetClusterStreamsResponse)
	err := c.cc.Invoke(ctx, "/pb.StreamService/GetClusterStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetOptimalNodeForPublisher(ctx context.Context, in *GetOptimalNodeForPublisherRequest, opts ...grpc.CallOption) (*GetOptimalNodeForPublisherResponse, error) {
	out := new(GetOptimalNodeForPublisherResponse)
	err := c.cc.Invoke(ctx, "/pb.StreamService/GetOptimalNodeForPublisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetOptimalNodeForSubscriber(ctx context.Context, in *GetOptimalNodeForSubscriberRequest, opts ...grpc.CallOption) (*GetOptimalNodeForSubscriberResponse, error) {
	out := new(GetOptimalNodeForSubscriberResponse)
	err := c.cc.Invoke(ctx, "/pb.StreamService/GetOptimalNodeForSubscriber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) UpdateStreamState(ctx context.Context, in *UpdateStreamStateRequest, opts ...grpc.CallOption) (*UpdateStreamStateResponse, error) {
	out := new(UpdateStreamStateResponse)
	err := c.cc.Invoke(ctx, "/pb.StreamService/UpdateStreamState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility
type StreamServiceServer interface {
	// 注册流
	RegisterStream(context.Context, *RegisterStreamRequest) (*RegisterStreamResponse, error)
	// 注销流
	UnregisterStream(context.Context, *UnregisterStreamRequest) (*UnregisterStreamResponse, error)
	// 获取流信息
	GetStreamInfo(context.Context, *GetStreamInfoRequest) (*GetStreamInfoResponse, error)
	// 获取集群流列表
	GetClusterStreams(context.Context, *GetClusterStreamsRequest) (*GetClusterStreamsResponse, error)
	// 获取发布者最优节点
	GetOptimalNodeForPublisher(context.Context, *GetOptimalNodeForPublisherRequest) (*GetOptimalNodeForPublisherResponse, error)
	// 获取订阅者最优节点
	GetOptimalNodeForSubscriber(context.Context, *GetOptimalNodeForSubscriberRequest) (*GetOptimalNodeForSubscriberResponse, error)
	// 更新流状态
	UpdateStreamState(context.Context, *UpdateStreamStateRequest) (*UpdateStreamStateResponse, error)
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (UnimplementedStreamServiceServer) RegisterStream(context.Context, *RegisterStreamRequest) (*RegisterStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterStream not implemented")
}
func (UnimplementedStreamServiceServer) UnregisterStream(context.Context, *UnregisterStreamRequest) (*UnregisterStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterStream not implemented")
}
func (UnimplementedStreamServiceServer) GetStreamInfo(context.Context, *GetStreamInfoRequest) (*GetStreamInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamInfo not implemented")
}
func (UnimplementedStreamServiceServer) GetClusterStreams(context.Context, *GetClusterStreamsRequest) (*GetClusterStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStreams not implemented")
}
func (UnimplementedStreamServiceServer) GetOptimalNodeForPublisher(context.Context, *GetOptimalNodeForPublisherRequest) (*GetOptimalNodeForPublisherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOptimalNodeForPublisher not implemented")
}
func (UnimplementedStreamServiceServer) GetOptimalNodeForSubscriber(context.Context, *GetOptimalNodeForSubscriberRequest) (*GetOptimalNodeForSubscriberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOptimalNodeForSubscriber not implemented")
}
func (UnimplementedStreamServiceServer) UpdateStreamState(context.Context, *UpdateStreamStateRequest) (*UpdateStreamStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStreamState not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_RegisterStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).RegisterStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StreamService/RegisterStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).RegisterStream(ctx, req.(*RegisterStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_UnregisterStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).UnregisterStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StreamService/UnregisterStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).UnregisterStream(ctx, req.(*UnregisterStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetStreamInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetStreamInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StreamService/GetStreamInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetStreamInfo(ctx, req.(*GetStreamInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetClusterStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetClusterStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StreamService/GetClusterStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetClusterStreams(ctx, req.(*GetClusterStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetOptimalNodeForPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptimalNodeForPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetOptimalNodeForPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StreamService/GetOptimalNodeForPublisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetOptimalNodeForPublisher(ctx, req.(*GetOptimalNodeForPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetOptimalNodeForSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptimalNodeForSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetOptimalNodeForSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StreamService/GetOptimalNodeForSubscriber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetOptimalNodeForSubscriber(ctx, req.(*GetOptimalNodeForSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_UpdateStreamState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStreamStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).UpdateStreamState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StreamService/UpdateStreamState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).UpdateStreamState(ctx, req.(*UpdateStreamStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterStream",
			Handler:    _StreamService_RegisterStream_Handler,
		},
		{
			MethodName: "UnregisterStream",
			Handler:    _StreamService_UnregisterStream_Handler,
		},
		{
			MethodName: "GetStreamInfo",
			Handler:    _StreamService_GetStreamInfo_Handler,
		},
		{
			MethodName: "GetClusterStreams",
			Handler:    _StreamService_GetClusterStreams_Handler,
		},
		{
			MethodName: "GetOptimalNodeForPublisher",
			Handler:    _StreamService_GetOptimalNodeForPublisher_Handler,
		},
		{
			MethodName: "GetOptimalNodeForSubscriber",
			Handler:    _StreamService_GetOptimalNodeForSubscriber_Handler,
		},
		{
			MethodName: "UpdateStreamState",
			Handler:    _StreamService_UpdateStreamState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stream.proto",
}
